package telas;

import atividade.pkg3.uc9.Consulta;

import javax.swing.JOptionPane;

public class TelaFinalizarConsulta extends javax.swing.JFrame {

    private TelaInicial telaInicial;

    public TelaFinalizarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDetalhes = new javax.swing.JLabel();
        cbConsultaRealizada = new javax.swing.JCheckBox();
        lblReceita = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textReceita = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDetalhes.setForeground(new java.awt.Color(0, 0, 0));
        lblDetalhes.setText("Detalhes da consulta");

        cbConsultaRealizada.setBackground(new java.awt.Color(255, 255, 255));
        cbConsultaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbConsultaRealizada.setForeground(new java.awt.Color(0, 0, 0));
        cbConsultaRealizada.setText("Consulta Realizada");
        cbConsultaRealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultaRealizadaActionPerformed(evt);
            }
        });

        lblReceita.setBackground(new java.awt.Color(255, 255, 255));
        lblReceita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReceita.setForeground(new java.awt.Color(0, 0, 0));
        lblReceita.setText("Receita e Observações:");

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textReceita.setBackground(new java.awt.Color(255, 255, 255));
        textReceita.setColumns(20);
        textReceita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textReceita.setForeground(new java.awt.Color(0, 0, 0));
        textReceita.setLineWrap(true);
        textReceita.setRows(5);
        textReceita.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textReceitaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(textReceita);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetalhes)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblReceita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbConsultaRealizada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalhes)
                .addGap(18, 18, 18)
                .addComponent(cbConsultaRealizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try {
            if (textReceita.getText().isEmpty()) {
                throw new RuntimeException("O campo Receita e Observações está vazio");
            }
            Consulta consulta = telaInicial.pacientesList.get(telaInicial.posicaoPaciente());
            consulta.setReceita(textReceita.getText());
            telaInicial.atualizarTabela();
            
            dispose();
            
        } catch (RuntimeException e) {
            
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void cbConsultaRealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultaRealizadaActionPerformed
        if (cbConsultaRealizada.isSelected()) {
            
            Consulta consulta = telaInicial.pacientesList.get(telaInicial.posicaoPaciente());
            consulta.setConsultaFinalizada("Sim");
        }
    }//GEN-LAST:event_cbConsultaRealizadaActionPerformed

    private void textReceitaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textReceitaAncestorAdded
        Consulta consulta = telaInicial.pacientesList.get(telaInicial.posicaoPaciente());
        if (consulta.getConsultaFinalizada() == "Sim") {
            
            textReceita.setText(consulta.getReceita());
            textReceita.setEditable(false);
        }
    }//GEN-LAST:event_textReceitaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinalizarConsulta().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox cbConsultaRealizada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetalhes;
    private javax.swing.JLabel lblReceita;
    private javax.swing.JTextArea textReceita;
    // End of variables declaration//GEN-END:variables

    public void mostrarTela(TelaInicial tela) {
        this.telaInicial = tela;
        setVisible(true);
    }

    public void marcarCheckBox() {  
        cbConsultaRealizada.setSelected(true);
    }
    
    public void desabilitarCheckBox(){
        cbConsultaRealizada.setEnabled(false);
    }

    public void esconderBotaoFinalizar() {
        btnFinalizar.setEnabled(false);
        btnFinalizar.setVisible(false);
    }
}
